---
- name: Prepare GUID environment variable across all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc
  tags:
    - config

#- name: Verify Installation and Configuration of Docker
#  hosts: nodes
#  tasks:
#    - name: docker restart
#      shell: systemctl restart docker

#- name: Verify NFS Shared Volumes on Hosts
#  hosts: nfs
#  tasks:

#- name: Install packages and config auth
#  hosts: localhost
#  vars_files:
#    - "./env_vars.yml"
#  tasks:
#    - name: required packages are present
#      yum:
#        name: "{{ common_packages }}"
#        state: present


- name: Generate Inventory Hosts File from template
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - "./env_vars.yml"
  tasks:
    - name: Generate /etc/ansible/hosts file with lab hosts template
      template:
        backup: yes
        src: "./hoststempl.j2"
        dest: "/etc/ansible/hosts"

  tags:
    - config


- name: Execute the openshift-ansible prerequisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  tags:
    - install

- name: Execute the openshift-ansible Deployer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
  tags:
    - install

- name: Verify OpenShift Cluster
  hosts: masters[0]
  tasks:
    - name: copy the .kube directory from master1 to your bastion
      fetch: 
        src: "/root/.kube/config"
        dest: "/root/.kube/config"
        flat: "yes"
  tags:
    - postinst

- name: Post installation configuration
  hosts: localhost
  tasks:
    - name: make sure you are system:dmin
      shell: oc whoami | grep system:admin
  tags:
    - postinst

- name: Create PVs for Users
  hosts: nfs
  tasks:
    - file:
        dest: "/srv/nfs/user-vols/pv{{ item }}"
        state: directory
      with_sequence: start=1 end=50 stride=1
    - lineinfile:
        path: /etc/exports.d/openshift-uservols.exports
        line: "/srv/nfs/user-vols/pv{{ item }} *(rw,root_squash)"
        create: yes
      with_sequence: start=1 end=50 stride=1
    - systemd:
        state: restarted
        daemon_reload: yes
        name: nfs-server
    - file:
        path: /srv/nfs
        state: directory
        owner: nfsnobody
        group: nfsnobody
        mode: 0777
        recurse: yes
  tags:
    - postinst

- name: Create 25 definitions files for PVs 5G size
  hosts: localhost
  tasks:
    - name: "create def files for 5G PVs"
      shell: "./scripts/pvs_5Gsize.sh"
  tags:
    - postinst

- name: Create 25 definitions files for PVs 10G size
  hosts: localhost
  tasks:
    - name: "create def files for 10G PVs"
      shell: "./scripts/pvs_10Gsize.sh"
  tags:
    - postinst

- name: Create all PVs from definitions files
  hosts: localhost
  tasks:
    - name: "import files"
      shell: "cat /root/pvs/* | oc create -f -"
  tags:
    - postinst

- name: Fix NFS Persistent Volume Recycling
  hosts: nodes
  tasks:
    - name: "fix commands for NFS persistent volume recycling"
      shell: "docker pull registry.access.redhat.com/openshift3/ose-recycler:latest && docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30"

  tags:
    - postinst

- name: Smoke Test
  hosts: localhost
  tasks:
    - name: "Smoke testing with nodejs app"
      shell: "oc new-project smoke-test && oc new-app nodejs-mongo-persistent"
      
  tags:
    - smoketest

#- name: Jenkins Setup
#  hosts: localhost
#  tasks:
#    - name: jenkins setup
#      script: ???

#- name: HPA configuration on production deployment of openshift-tasks
#  hosts: localhost
#  tasks:

#- name: Creation of users for Alpha and Beta clients

#- name: Assigning labels to the users according to its group

#- name: Setup the environment for Alpha and Beta clients