apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "tasks-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "400m"
        memory: "6Mi"
    - type: "Container"
      max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "200m"
        memory: "4Mi"
      default:
        cpu: "700m"
        memory: "500Mi"
      defaultRequest:
        cpu: "500m"
        memory: "250Mi"
      maxLimitRequestRatio:
        cpu: "10"